# Generated by Django 5.2.7 on 2025-10-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;")
    ]
