# Generated by Django 5.2.7 on 2025-10-31 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title_fr', models.CharField(max_length=160)),
                ('title_en', models.CharField(blank=True, max_length=160, null=True)),
                ('categorie', models.CharField(choices=[('math', 'Mathématiques'), ('info', 'Informatique'), ('reseaux', 'Réseaux'), ('systemes', 'Systèmes'), ('langues', 'Langues'), ('autre', 'Autre')], max_length=16)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('norm_label', models.CharField(db_index=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['norm_label'], name='matcher_sub_norm_la_84ab9b_idx'), models.Index(fields=['code'], name='matcher_sub_code_a512d0_idx'), models.Index(fields=['categorie', 'level'], name='matcher_sub_categor_5607a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=180)),
                ('norm_label', models.CharField(db_index=True, max_length=180)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('und', 'Indéterminé')], default='fr', max_length=8)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='matcher.subjecttarget')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'norm_label'], name='matcher_sub_languag_bc9ccd_idx'), models.Index(fields=['norm_label'], name='matcher_sub_norm_la_213f10_idx')],
                'unique_together': {('target', 'norm_label', 'language')},
            },
        ),
    ]
