# Generated by Django 5.2.7 on 2025-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttarget',
            name='coef',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
